language: node_js
node_js:
  - "10"

cache: yarn

branches:
  only:
    - master

install:
  - yarn
  - yarn export-gh-pages
  - yarn generateSW

after_install:
  - cp sw.html out

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  local-dir: out
  on:
    branch: master
